anymal:

  floating_base_controller:
    type: anymal_c_simple_description/floating_base_controller
    joint_names:
         - LF_HAA
         - LF_HFE
         - LF_KFE
         - LH_HAA
         - LH_HFE
         - LH_KFE
         - RF_HAA
         - RF_HFE
         - RF_KFE
         - RH_HAA
         - RH_HFE
         - RH_KFE
